### PR TITLE
Consolidate `_stdlib_random` functions

### PR DESCRIPTION
**Pull request by benrimmington**

### CODE REVIEW

**Comment by benrimmington** [comment]
One of the tests will fail, with "Fatal error: Division by zero in remainder operation".

```diff
 RandomTests.test("random floating points in ranges") {
   floatingPointRangeTest(Float.self)
   floatingPointRangeTest(Double.self)
-  floatingPointRangeTest(Float80.self)
 }
```

Your previous workaround was also needed, in order to compile and test.

```diff
-  public func random<T: RandomNumberGenerator>(
-    using generator: T
+  public func random(
+    using generator: RandomNumberGenerator
   ) -> Element? {
```

**Comment by Azoy** [comment]
This looks great, thanks! However, is changing the generator this late in the review process acceptable? I don't really see why this would be controversial, but it does alter that from what the reviewers have seen.

Nate's pr moves this failing test into its own test, and the compilation error is fixed in his pr as well.

**Comment by benrimmington** [comment]
I've rebased and updated, to use:

* `getrandom` (Android, Cygwin, Linux) or `getentropy` (Fuchsia);
* "/dev/urandom" as a last resort (ENOSYS, FreeBSD, Haiku, etc.)

I think it's now close enough to your [proposed solution](https://github.com/apple/swift-evolution/blob/master/proposals/0202-random-unification.md#proposed-solution).

**Comment by benrimmington** [comment]
@Azoy, should we use "/dev/urandom" instead of [`SecRandomCopyBytes`](https://developer.apple.com/documentation/security/randomization_services)?

* <https://forums.swift.org/t/se-0202-random-unification/11313/128>
* <https://forums.swift.org/t/se-0202-random-unification/11313/149>

**Comment by Azoy** [comment]
Sorry for being a bit inactive! Yeah, I was thinking about going with that approach, but my concern is that the device file is not present on simulators due to sandboxing. I'm not sure if you can make that distinction and can use `SecRandomCopyBytes` for simulators.

**Comment by benrimmington** [comment]
Using "/dev/urandom" seems to work in the *iOS 8.1 Simulator* (the oldest available for the latest Xcode).

If sandboxing is an issue, we could use `arc4random_buf` in the simulator, to avoid the Security framework dependency.

There's a `TARGET_OS_SIMULATOR` macro in `<TargetConditionals.h>`, or a new [`__APPLE_EMBEDDED_SIMULATOR__`](http://llvm.org/svn/llvm-project/cfe/trunk/lib/Frontend/InitPreprocessor.cpp) macro in Clang.

**Comment by Azoy** [comment]
I imagine the proposal will be revised to not explicitly state the specific implementations for each platform, but rather describe that platforms will be secure. This means we have more flexibility over how we choose the secure generators for the future. I think if it does get revised to something along those lines, we can look at using `/dev/urandom` for older versions of Darwin. This also means we could potentially use the portable `getentropy(3)` and simplify a lot of code. I want to hear back from the team to see their decision first regarding that issue before merging this pr.

**Comment by benrimmington** [comment]
I've removed `SecRandomCopyBytes` in Azoy/swift@d9e2017541f539055b402377d947b7715f633a86 (but it can be reverted before merging).

I thought using `getentropy` on Android/Cygwin/Linux would be simpler, because it hides `EINTR` errors, but those have to be handled for "/dev/urandom" anyway.

**Comment by Azoy** [comment]
Question, should we cache actual_bytes if it returns -1? Example: if we call `getrandom(2)` and we get a `ENOSYS`, should that be cached for the whole application that way we don't have to call `getrandom(2)` each time?

**Comment by benrimmington** [comment]
We can do, if you think there will be a measurable difference.

```diff
 #if defined(GRND_RANDOM)
+    static const bool getrandom_available =
+      !(getrandom(nullptr, 0, 0) == -1 && errno == ENOSYS);
+    if (getrandom_available) {
       actual_nbytes = WHILE_EINTR(getrandom(buf, nbytes, 0));
+    }
 #elif defined(__Fuchsia__)
```

**Comment by benrimmington** [comment]
When opening "/dev/urandom", should we use the `O_NOFOLLOW` and `O_CLOEXEC` flags?

`SecRandomCopyBytes` for [macOS 10.9](https://opensource.apple.com/source/Security/Security-55471/sec/Security/SecFramework.c.auto.html) was a "/dev/random" wrapper, but on [macOS 10.10 & 10.11](https://opensource.apple.com/source/Security/Security-57336.1.9/OSX/sec/Security/SecFramework.c.auto.html) (and later versions) it uses `CCRandomCopyBytes` instead.

When reading `uint64_t` values (using a million `_stdlib_random` calls), compared with the current `SecRandomCopyBytes`:

- "/dev/urandom" is 5x faster,
- `arc4random_buf` is 16x faster.

I've searched for any mention of the iOS sandbox issue. There are some [comments](https://mikeash.com/pyblog/friday-qa-2011-03-18-random-numbers.html#comments) in an article from March 2011 (iOS 4). But it's difficult to find anything specifically about iOS 7, 8 or 9.

**Comment by Azoy** [comment]
Yeah I think we ought to go ahead with caching the return value of `getrandom(2)` in case it doesn't exist. I think you should also check for `EUNSUPP` `(errno == ENOSYS || errno == EUNSUPP)`. If you think adding the flags during opening `/dev/urandom` is a good idea, then I agree. Maybe I was wrong with the sandboxing issue, awesome! After you push those, I think this would be ready to merge.

**Comment by benrimmington** [comment]
`EUNSUPP` doesn't seem to be a standard error. I can't find it in any `<sys/errno.h>` headers.
